apiVersion: apps/v1
kind: Deployment
metadata:
  name: brmysql
  labels:
    app: brmysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brmysql
  template:
    metadata:
      labels:
        app: brmysql
    spec:
      containers:
      - name: brmysql
        image: mysql:5.7.38
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: brmysql-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: brmysql-secret
                key: MYSQL_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: brmysql-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: brmysql-configmap
                key: MYSQL_HOST
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: brmysql-configmap
                key: MYSQL_DATABASE
          - name: MYSQL_TCP_PORT
            valueFrom:
              configMapKeyRef:
                name: brmysql-configmap
                key: MYSQL_TCP_PORT
        volumeMounts:
        - mountPath: "/var/lib/mysql/data"
          name: brmysql-pv
      volumes:
        - name: brmysql-pv
          persistentVolumeClaim:
            claimName: brmysql-pvc